- hosts: vm1
  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Install Apache
    yum:
      name: httpd
      state: latest

  - name: Make sure a service is running
    systemd:
      state: started
      enabled: yes
      name: httpd

  - name: Download template
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page292/honey.zip
      dest: /tmp/honey.zip

  - name: Install Unzip
    yum:
      name: unzip
      state: latest

  - name: Extract a template
    unarchive:
      src: /tmp/honey.zip
      dest: /tmp/
      remote_src: yes

  - name: Move templates files to /var/www/html
    shell: "mv /tmp/honey-html/* /var/www/html/"
    args:
      creates: /var/www/html/index.html 

  - name: Give insecure permissions to an existing file
    file:
      path: /var/www/html
      owner: apache
      group: apache
      recurse: yes



 

 